services:
    app.service.cuenation.cue_categories:
        class: AppBundle\Service\CueNation\CueCategories
        arguments:
            - "@app.client"
        calls:
            - [setEnvironment, ["%kernel.environment%"]]